main: un10.un10.Main
name: Synthesis
version: ${project.version}
api-version: 1.16
authors: [UN10]
default-permission: false
description: Minecraft UXG Survival server plugin.
website: https://www.youtube.com/channel/UCKqkBId-ffhILwW9O8zVcqw
permissions:
  sp.*:
    description: sp plugin all permission
    default: op
  sp.chatting:
    description: server chatting permission
    default: op
  sp.broadcast:
    description: broadcast permission
    default: op
  sp.teleport:
    description: teleport world permission
    default: op
  sp.ts:
    description: Team Selector
    default: op
  sp.gm:
    description: gameMode change permission
    default: op
  sp.shutdown:
    description: shutDown server command
    default: op
  sp.createNPC:
    description: create npc permission
    default: op
  sp.setdpname:
    description: set display name
    default: op
  sp.particle:
    description: redstone particle
    default: op
  sp.turret:
    description: create turret
    default: op
  sp.wcontrol:
    description: world controller
    default: op
  sp.wteleport:
    description: world telepoter
    default: op
  sp.ban:
    description: banning player
    default: op
commands:
  broadcaster:
    description: "broadcast, Need permission : sp.broadcast or sp.*"
    usage: "/<command> <message>"
    permission: sp.broadcast
    permission-message: "you don't have permission."
  math:
    description: "Math!! I don't like!"
    usage: "/<command> <Integer> *,/,-,+,^ <Integer>"
  gm:
    description: "gameMode change command"
    usage: "/<command> <0 | 1 | 2 | 3> [player]"
    permission: sp.gm
    permission-message: "you don't have permission."
  code:
    description: "special code."
    usage: "/<command> <code>"
  whisper:
    description: "whisper~ whisper~ you're friend whisper!"
    aliases: [w, 귓, 귓속말]
    usage: "/<command> <OnlinePlayer> <message>"
  shutDown:
    description: "Shutdown server."
    permission: sp.shutdown
    permission-message: "you don't have permission."
    usage: "/<command> <count> <message>"
  setWorld:
    description: "weather, time"
    usage: "/<command>"
  cn:
    description: "create NPC"
    usage: "/<command> <player> <name>"
    permission: sp.createNPC
    permission-message: "you don't have permission."
  sd:
    description: "set display name"
    usage: "/<command> [name] <displayname>"
    permission: sp.setdpname
    permission-message: "you don't have permission."
  cw:
    description: "create world"
    usage: "/<command> <name> <type> [seed]"
    permission: sp.control
    permission-message: "you don't have permission."
  wt:
    description: "world teleport"
    usage: "/<command> <name>"
    permission: sp.wteleport
    permission-message: "you don't have permission."
  bangui:
    description: "ban player."
    usage: "/<command>"
    permission: sp.ban
    permission-message: "you don't have permission."